services:
  - type: web
    name: ai-sentiment-analyzer
    env: docker
    plan: free
    dockerImage: patilvirupakshi/ai-sentiment-analyzer:latest
    region: oregon
    envVars:
      - key: PORT
        value: 5000
